AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  Include:
    - '**/*.lic'
    - '**/*.rb'

Naming/FileName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false
  
Style/BlockComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
