---
# See https://github.com/rpherbig/dr-scripts/wiki/YAML-Settings for documentation

hometown: Crossing
training_manager_town_duration:

# Combat settings
aim_fillers:
  Crossbow:
  - bob
  - bob
  Bow:
  - bob
  - bob
  - bob
  Slings:
  - bob
  - bob
  - bob
stances:
  Bow:
  - Evasion
  - Shield Usage
  - Parry Ability
  Crossbow:
  - Evasion
  - Shield Usage
  - Parry Ability
  Slings:
  - Evasion
  - Shield Usage
  - Parry Ability
  Offhand Weapon:
  - Evasion
  - Shield Usage
  - Parry Ability
default_stance: 100 0 80
stance_override:
cycle_armors:
cycle_armors_time: 125
skinning:
  skin: true
  arrange_all: false
  arrange_count: 0
  tie_bundle: false
charged_maneuvers:
  Brawling: palmstrike
  Bow: powershot
  Crossbow: powershot
  Slings: powershot
  Small Edged: cleave
  Large Edged: cleave
  Twohanded Edged: cleave
  Small Blunt: crash
  Large Blunt: crash
  Twohanded Blunt: crash
  Staves: twirl
  Polearms: impale
  Dual Wield: doublestrike
dance_threshold: 0
dance_skill: Small Edged
dynamic_dance_skill: false
dance_actions:
- analyze
- circle
- bob
- weave
combat_analyze_retry_count: 3
manipulate_threshold:
manipulate_only_to_train: false
training_abilities:
  Hunt: 80
combat_training_abilities_target: 32
favor_orb_rub_frequency: 300
fatigue_regen_threshold: 90
fatigue_regen_action: bob
balance_regen_threshold: 8 #solidly balanced
summoned_weapons:
summoned_weapons_element:
summoned_weapons_ingot:
buff_spells:
offensive_spells:
offensive_spell_cycle:
aim_fillers_stealth:
buff_nonspells:
dance_actions_stealth:
thanatology:
dissect_and_butcher: false
necro_force_safe_room: false
necro_siphon_vit_threshold: 85
necro_safe_room_use_devour: false
necromancer_healing:
  wound_level_threshold: 1 # 1 - 8
zombie:
  make: false
  summon: false
  stance: offense
  behavior: defensive
weapon_training:
combat_trainer_target_increment: 3
combat_trainer_action_count: 10
dual_load: false
use_stealth_attacks: false
stealth_attack_aimed_action: poach
hide_type: hide
force_unhide: false
skip_last_kill: false
backstab:
ambush: false
performance_monitor_weapons:
retreat_threshold:
use_weak_attacks: false
loot_bodies: true
dump_junk: false
dump_item_count: 9
use_barb_combos: false
whirlwind_trainables:
combat_spell_training_max_threshold:
offensive_spell_mana_threshold: 40
training_spell_mana_threshold: 50
buff_spell_mana_threshold: 40
stun_weapon:
stun_weapon_skill:
stun_skill: Debilitation
dont_stalk: false
cast_only_to_train: false
priority_weapons:
priority_defense:
tk_ammo:
custom_loot_type:
last_rites: false
ambush_location: back
warhorn:
prayer_mat:
paladin_use_mana_glyph: false
paladin_use_badge: false
offhand_thrown: false

# Hunting settings
training_manager_hunting_priority: false
training_manager_priority_skills:
priority_skills_lower_limit: 6
hunting_info:
empty_hunting_room_messages:
- Is anyone else in here?
- I hope no one else is here, I really want to kill something.
- Is anyone hunting here? Speak now or hold your peace.
- This looks like a good room. I hope I'm not taking it from anyone.
- My eyes aren't so good. Did I miss someone in the room?
hunting_buddies:
stop_hunting_if_bleeding: true
prehunt_buffs:
hunting_room_min_mana: 0
hunting_room_strict_mana: false
hunting_file_list:



# Repair settings
repair_withdrawal_amount: 10_000
skip_repair: false
repair_timer: 600
repair_every: 1




# Safe-room settings
safe_room_id:
safe_room_take:
safe_room_give:
safe_room_tip_threshold:
safe_room_tip_amount:
safe_room_empath:
safe_room_empaths:




# Spellcasting (and Khri) settings
use_harness_when_arcana_locked: false
combat_trainer_buffs_force_cambrinth: true
crossing_training_force_cambrinth: false
waggle_force_cambrinth: true
cambrinth: armband
cambrinth_cap: 32
stored_cambrinth: false
prep_scaling_factor: 0.98
kneel_khri: false
cambrinth_items:
- name:
  cap:
  stored:
cambrinth_num_charges: 4  #Number of times to charge a cambrinth item with use_auto_mana
cambrinth_invoke_exact_amount: false



# Looting settings
loot_additions:
loot_subtractions:
loot_specials:
box_loot_limit:
box_hunt_minimum: 1



# Non-combat settings
exp_timers:
  Stealth: 300
  First Aid: 400
  Locksmithing: 600
  Theurgy: 720
  Thievery: 600
  Attunement: 130
listen: false
listen_observe: false
safe_room: 851
hide_to_steal: true
bin_stolen: false
slow_bin_speed: false
hand_armor: gloves
instrument:
footwear:
exit_on_skills_capped: false
crossing_training_sorcery:
crossing_training_sorcery_room: 1137
crossing_training_requires_movement:
- Alchemy
- Appraisal
- Athletics
- Attunement
- Empathy
- Engineering
- Forging
- Outfitting
- Scouting
- Sorcery
- Stealth
- Thievery
- Theurgy
- Trading
forage_item: rock
braid_item:
training_spells:
cyclic_training_spells:
cyclic_cycle_skills:
train_with_spells: true
training_nonspells:
crossing_training:
use_research: false
research_skills:
water_holder:
flint_lighter:
scouting_buffs:
crossing_training_stationary_skills_only: false
outdoor_room: 793
textbook: false
textbook_type: textbook
dedicated_camb_use:
symbiosis_learning_threshold: 2
compost_room: 991
mine_for_outdoorsmanship: false
appraisal_training:
- art
full_pouch_container:
classes_to_teach:
avoid_athletics_in_justice: false
athletics_outdoorsmanship_rooms:
attunement_rooms:
training_rooms:




# Stealing settings
stealing_bag: backpack
stealing_high_acceptable_count: 1
stealing_low_acceptable_count: 2
steal_past_mindlock: false
stealing_buffs:
npc_stealing_attempt_count: 0
dont_steal_list:
stealing_towns:
  - Crossing
  - Arthe Dale
  - Kaerna Village
  - Tiger Clan
  - Knife Clan
  - Dirge # Ya madmen
#  - Leth Deriel
#  - Shard
#  - Horse Clan
#  - Aesry


# Crafting settings
crafting_container: backpack
crafting_items_in_container:
forging_tools:
- diagonal-peen hammer
- tong
- bellow
- shovel
knitting_tools:
- knitting needle
shaping_tools:
- carving knife
- shaper
- drawknife
- rasp
alchemy_tools:
- mortar
- pestle
- bowl
- mixing stick
- sieve
carving_tools:
- chisels
- rifflers
- rasp
forging_belt:
engineering_belt:
outfitting_belt:
alchemy_belt:
mark_crafted_goods: false
engineering_room:
outfitting_room:
alchemy_room:
use_own_ingot_type:
deed_own_ingot: false
crafting_training_spells:



# Workorder settings
train_workorders:
work_order_disciplines:
workorder_diff: challenging
carving_workorder_material_type: stone
workorder_min_items: 2
workorder_max_items: 3
workorder_recipes:




# Lumber settings
forests_to_chop:
- neg_to_kaerna
- cougars
lumber_skip_populated: true
lumber_buddy_chop_every_room: false
lumber_buddy_tree_list:
# common
- Ash #shortbows
- Bamboo # martial
- Durian # martial
- Mahogany # martial
- Mangrove #martial, shortbows
- Maple #longbows
- Sandalwood #Composite
# rare
- Adder # Alterations
- Aformosia # Alterations
- Albarco # shortbow
- Alerce # Alterations
- Avodire # composite
- Azurelle # longbows
- Bloodwood # longbows, shortbows
- Bocote # martial
- Cherry # longbows
- Copperwood # longbows
- Crabwood # martial
- Darkspine	# martial
- Diamondwood # martial
- Dragonwood # alterations
- E'erdream # ???
- Felwood # martial, shortbows, composite
- Finivire # all bows
- Glitvire # ???
- Gloomwood # ???
- Goldwood # longbows, shortbows
- Greenheart # martial
- Hickory # martial, composite
- Ilomba # Alterations
- Iroko # Alterations
- Ironwood #martial
- Kapok # alterations
- Lelori #Composite
- Macawood #alterations
- Mistwood # longbow, shortbow
- Osage	# longbows
- Ramin # longbows
- Redwood # alterations
- Rockwood # martial
- Rosewood # longbows
- Shadowbark # ???
- Silverwood # shortbows, composite bows
- Smokewood	# alterations
- Tamarak # alterations
- Tamboti # ???
- Yew # Longbows
lumber_implement: axe
lumber_use_packet: true
lumber_while_training: false




# Mining settings
mines_to_mine:
- wicked_burrow
- stone_clan
- waterfall
mining_skip_populated: true
mining_buddy_mine_every_room: false
mining_buddy_vein_list:
# common
- Covellite
- Lead
- Silver
# alchemy
- Electrum
- Kadepa
- Muracite
- Niello
- Niniam
- Orichalcum
# forging
- Aldamdin
- Animite
- Audrualm
- Damite
- Darkstone
- Glaes
- Haledroth
- Haralun
- Icesteel
- Indurium
- Kertig
- Kiralan
- Lumium
- Platinum
- Quelium
- Silversteel
- Telothian
- Tyrium
- Vardite
- Yellow gold
# engineering
# common
# - Obsidian
# - Quartize
# rare
- Anjisis
- Belzune
- Blackwater jet
- Diamondique
- Felstone
- Fulginode
- Senci
- Xenomite
mining_ignored_stone_sizes:
- pebble
mining_implement: shovel
mine_use_packet: true
mine_while_training: false




# Lockpicking settings
stop_pick_on_mindlock: true
pick_blind: false
use_lockpick_ring: true
skip_lockpick_ring_refill: false
lockpick_container: ring
lockpick_type: ordinary
harvest_traps: true
picking_box_source: duffel bag
picking_box_storage:
picking_pet_box_source:
lockpick_dismantle:
lockpick_buffs:
lockpick_room_id:
lockpick_ignore_difficulty: false

# Bankbot Settings
bankbot_name:
bankbot_room_id:
bankbot_deposit_threshold: 0
bankbot_enabled: false

# Sell loot settings
sell_loot_pouch: true
sell_loot_bundle: true
sell_loot_money_on_hand: 3 silver
sell_loot_skip_bank: false
sell_pouches_for_trading: false
sale_pouches_container: backpack




# Misc settings
storage_containers:
gear:
gear_sets:
empath_healing:
saferoom_health_threshold: 0

restock:

osrel_no_harness: false
osrel_amount:

tie_gem_pouches: true
spare_gem_pouch_container:
gem_pouch_adjective:

trail_override:
ignored_npcs:

favor_god: Hodierna
immortal_aspect:
favor_goal:
theurgy_supply_container: backpack

writing_instrument:

tithe: false
tithe_almsbox:

cleaning_cloth: chamois cloth

listen_skills:
- Large Edged
- Twohanded Edged
- Small Blunt
- Light Thrown
- Brawling
- Offhand Weapon
- Melee Mastery
- Missile Mastery
- Life Magic
- Attunement
- Arcana
- Augmentation
- Utility
- Warding
- Athletics
- Perception
- First Aid
- Outdoorsmanship
- Scholarship
- Mechanical Lore
- Appraisal
- Performance
- Tactics
- Stealth
- Bows
- Evasion
- Parry Ability
- Small Edged
- Defending
- Light Armor
- Chain Armor
- Shield Usage
- Targeted Magic
- Debilitation
- Brigandine
- Plate Armor
- Large Blunt
- Twohanded Blunt
- Slings
- Crossbow
- Staves
- Polearms
- Heavy Thrown
- Locksmithing
- Skinning
- Forging
- Engineering
- Outfitting
- Alchemy

waggle_sets:

health_threshold: 50
depart_on_death: false
depart_type: item
afk_justice_threshold: 4
quit_on_status_warning: false
status_monitor_no_window: false
status_monitor_respond: true

lichbot_buffs:
lichbot_train_when_idle: false
lichbot_compost: false

lockpick_buff_bot:

slack_username:

darkbox_junk:
- sharkskin
- root
- rockweed
- kelp
- flowers
- apple
- strawberry
- root
- snake
- cobra
- coin
- belt
- powder
- sundress
- earcuff
- armband
- anklet
- sash
- ascot
- shirt
- cap
- cape
- ocarina
- tooth
- cloak
- pants
- headscarf
- belt
- boots
- tobacco
- trousers
- moccasins
- viper
- armband
- ring
- peach
- sandwich
- plum

darkbox_stop_on_wounded: false

pumpkin_junk:
- socks
- seeds
- muffin
- pumpkins
- shoe
- line
- ribbon
- necklace
- mask
- net
- cuff
- earcuff
- handker
- nose-stud
- pin
- armband
- wristlet
- necklace
- bracelet
- charm
- gold ring
- garter
- carving knife
- skeletons
- wormwood ring
- earrings
- steel ring
- scarf
- mug
- bracer
- copper button
- torque
- fuzzy bats
- blown-glass pumpkin
- plush maggot
- bandana
- gloves
- zombies
- jellybeans
- doll
- ghosts
- silver wristcuff
- cambrinth orb
- platinum ring
- cambrinth tart
- bloodstained fabric
- amulet
- figurine
- tankard
- green bracelet
- cambrinth peach
- cambrinth turnip
- pouch

grave_junk:
- flat stone
- scratched jawbone
- bone ring
- round stone
- pin
- shell
- rib
- finger
- slug
- tooth
- hair
- feather
- spleen
- shin bone
- spectacles
- linen
- parchment
- grub
- tail
- carapace
- jawbone
- ratskin
- earring
- ribbon
- deobar
- decayed skull
- rock
- hag
- cockroach
- hand-puppet
- mirror
- roll
- earthworms
- sweater
- sash
- gown
- socks
- veil
- blouse
- wedding
- bone shards
- sacrum
- rune-carved stone
- glowing fragment
- gloves
- intestines
- spine
- skull
- arm
- foreleg
- wing
- leg
- bone

climbing_target:
have_climbing_rope: false
# Astrology settings
astrology_buffs:
have_telescope: false
have_divination_bones: false
divination_bones_storage:
  container:
  tied:
astral_plane_training:
  train_in_ap: false  # Deprecated
  train_destination:
  train_source:
predict_event: false  # Deprecated
astrology_use_full_pools: false
astrology_pool_target: 1
astrology_training:
#- ways
- observe
- rtr
- weather
- attunement
#- moons #Deprecated
#- events

learned_column_count: 2
sort_auto_head: true

scroll_stackers:
- tome
discard_scrolls:
- Burden
- Dispel
- Ease Burden
- Gauge Flow
- Imbue
- Lay Ward
- Manifest Force
- Seal Cambrinth
- Strange Arrow
custom_scrolls:

theurgy_whitelist:
# Tithe 5 silver at the local almsbox.  Requres tithe: true
- tithe
# Study the wall in the Crossing temple.
- study_wall
# Meditate at the Crossing guild refectory
- refectory
# Carve a prayer bead.
- carve_bead
# Find and plant a sirese seed.
- sirese_seed
# Take a holy bath, you savage.
- bathe
# Pray on a prayer badge.
- pray_badge
# Medidate on a carved prayer bead.  Marvel at the special effects.
- meditate_bead
# Dance in front of an altar.
- dance
# Wave incense at an altar
- incense
# Pour wine on an altar.
- wine
# Recite the same prayer as everyone else in front of an altar.
- recite_prayer
# Clean an altar with holy water.
- clean_altar
# Clean your anloral pin.
- clean_anloral
# Read a prayer parchment in a populated place.
- embarass_myself
theurgy_blacklist:
# On second thought, let's not.
- embarass_myself
# theurgy_exp_threshold: 0 would run all possible things.
theurgy_exp_threshold: 33
theurgy_bead_carving_tool:
theurgy_use_prayer_mat: false
theurgy_prayer_mat_room:
pray_to_chadatru: false

trade_contract_container: backpack
dirt_stacker:

force_healer_town:
shard_thief_password:
forge_container:
spell_cycle:
